MVC/UdemyCodeFirstDBConnection/UdemyCodeFirstDBConnection/Controllers/Api/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using UdemyCodeFirstDBConnection.Models;
using UdemyCodeFirstDBConnection.ViewModel;
using UdemyCodeFirstDBConnection.CustomerDTO;
using AutoMapper;

namespace UdemyCodeFirstDBConnection.Controllers.Api
{   
    public class CustomersController : ApiController
    {
        private ApplicationDbContext _Context = null;

        public CustomersController()
        {
            _Context = new ApplicationDbContext();
        }
        //GET /api/Cutomers
        public IEnumerable<CustomersDTO> GetCustomersList()
        {
            return _Context.CustomerMode.ToList().Select(Mapper.Map<CustomerModel,CustomersDTO>);
        }

        //GET /api/Customers/1
        public CustomersDTO GetCustomer(int id)
        {
            var customer = _Context.CustomerMode.SingleOrDefault(c => c.CustID == id);
            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            return Mapper.Map<CustomerModel,CustomersDTO>(customer);
        }

        //POST /api/Customers
        [HttpPost]
        public IHttpActionResult CreateCustomers(CustomerModel Customer)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            _Context.CustomerMode.Add(Customer);
            _Context.SaveChanges();
            return Created(new Uri(Request.RequestUri+"/"+Customer.CustID),Customer);
        }

        //PUT /api/Customers/1
        [HttpPut]
        public void UpdateCustomer(int id, CustomerModel Customer)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            var CustomerInDB = _Context.CustomerMode.SingleOrDefault(m => m.CustID == id);
            CustomerInDB.CustName = Customer.CustName;
            CustomerInDB.BirthDate = Customer.BirthDate;
            CustomerInDB.IsSubscribedToNewsletter = Customer.IsSubscribedToNewsletter;
            CustomerInDB.MembershipTypeId = Customer.MembershipTypeId;
            _Context.SaveChanges();
        }

        [HttpDelete]
        public void DeleteCustomer(int id)
        {
            var Customer = _Context.CustomerMode.SingleOrDefault(c => c.CustID == id);
            if (Customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            _Context.CustomerMode.Remove(Customer);
            _Context.SaveChanges();
        }
    

    }
}

MVC/UdemyCodeFirstDBConnection/UdemyCodeFirstDBConnection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Customers Information</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Customers", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Customers Information</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>